# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a808b6465a7bdf724c2ca6e8d3f664c7048254f57cf662d53fe68c90ea7cc1201758868cb11879bd390eb9f360b6c25a67c648ca743ea06410dbed7e0aaa277

test:
  secret_key_base: f54e832c3166f69bf10192a780fa854889c28bf2fa19025d992be929bd3334d87a4e20b60ea1fce96775ee43866d919bbf4c0a2f5c80b0c3368fd513e8d5f173

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
